//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booked_Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booked_Ticket()
        {
            this.Canceled_Ticket = new HashSet<Canceled_Ticket>();
            this.Passengers = new HashSet<Passenger>();
        }
    
        public decimal PNR_No { get; set; }
        public Nullable<decimal> User_id { get; set; }
        public Nullable<decimal> Train_No { get; set; }
        public string Ticket_Class { get; set; }
        public double TotalFare { get; set; }
        public System.DateTime Booking_Date_Time { get; set; }
        public string Status { get; set; }
    
        public virtual Train_Details Train_Details { get; set; }
        public virtual User_details User_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Canceled_Ticket> Canceled_Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passenger> Passengers { get; set; }
    }
}
