//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canceled_Ticket
    {
        public int Canceled_id { get; set; }
        public Nullable<decimal> PNR_No { get; set; }
        public Nullable<decimal> User_id { get; set; }
        public Nullable<decimal> Train_No { get; set; }
        public Nullable<System.DateTime> Cancellation_Date_Time { get; set; }
        public Nullable<int> Refund_Ammount { get; set; }
    
        public virtual Booked_Ticket Booked_Ticket { get; set; }
        public virtual Train_Details Train_Details { get; set; }
        public virtual User_details User_details { get; set; }
    }
}
