//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Fare
    {
        public int Serial_No { get; set; }
        public decimal Train_No { get; set; }
        public double C1_A { get; set; }
        public double C2_A { get; set; }
        public double C3_A { get; set; }
        public double SL { get; set; }
    
        public virtual Train_Details Train_Details { get; set; }
    }
}
