//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public int P_Id { get; set; }
        public Nullable<decimal> PNR_No { get; set; }
        public string P_Name { get; set; }
        public Nullable<int> P_Age { get; set; }
    
        public virtual Booked_Ticket Booked_Ticket { get; set; }
    }
}
