//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_details()
        {
            this.Booked_Ticket = new HashSet<Booked_Ticket>();
            this.Canceled_Ticket = new HashSet<Canceled_Ticket>();
        }
    
        public decimal User_id { get; set; }
        public string User_Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Passcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booked_Ticket> Booked_Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Canceled_Ticket> Canceled_Ticket { get; set; }
    }
}
